### ISSUE TITLE
how to return Effect and StdErr in the output file

### ISSUE THREAD

**Issue by mikexjiang** [statgen/METAL#10]
May I ask what command I can use to return the Effect and StdErr in the output file? I have updated to the latest version: 2020-05-05. I understand that new options have been implemented to control the number of digits for Effect and StdErr in the output file. But currently, my output file can only output Z-score other than Effect and StdErr. May I know how to make it output Effect and StdErr as well?

Thank you very much in advance!

**Comment by mikexjiang** [comment]
I just realised that if I use the standard error as the weight (SCHEME   STDERR) other than the number of tested samples, the output will contain Effect and StdErr rather than Z-score. I am sorry for posting this naive question above.

**Comment by welchr** [comment]
No problem at all, glad you got it working.

**Comment by iamyingzhou** [comment]
When using SCHEME STDERR in my analysis, I noticed that the results are quite unusual , the effect sizes of certain SNPs appear to be exceedingly large.
