### ISSUE TITLE
##  ERROR: The command you issued could not be processed ...

### ISSUE THREAD

**Issue by AMCalejandro** [statgen/METAL#17]
Hi,

I am falling within the following error for one of my input GWAS files, and I cannot figure out what may be causing the issue.

        if (tokens.Length() == 1) {
            printf("##  ERROR: The command you issued could not be processed ...\n");
            continue;
        }

The commands applied to run metal for that specific file are:

SCHEME STDERR
AVERAGEFREQ ON
MINMAXFREQ ON
CUSTOMVARIABLE TotalSampleSize
LABEL TotalSampleSize as Nsample 

......

# === DESCRIBE AND PROCESS PDSTAT ===
MARKER SNP
ALLELE A1 A2
FREQ   MAF
EFFECT Coeff
STDERR se
#PVALUE p.value
#WEIGHT N
PROCESS ../PDSTAT/RESULTS_TIDY/modelbasic/PDSTAT_modelBasic_total.txt

OUTFILE metal_pdstat.ppmi.proband.opdc_totalOutcome.tbl
ANALYZE HETEROGENEITY

QUIT

The header of the file....

<pre>SNP	CHR	BP	A1	A2	Coeff	se	tVal	pVal	BIC	MargR2	CondR2	N	OutcomeVar	MAF	Nsample
rs3131972	1	752721	A	G	0.0973184269099255	2.67166182127882	0.036426177196088	0.971001390250452	2825.86652627283	0.0500525556109709	0.727862513155491	359	modelBasic_total	0.125	124
rs11240777	1	798959	A	G	-2.14252697297112	2.3854162409976	-0.898177406587578	0.370844019013569	2825.06389682483	0.0551317431253653	0.727815810596432	359	modelBasic_total	0.1452	124
rs149737509	1	837657	C	G	6.60417605349683	7.71465092921372	0.856056367824529	0.393608058617525	2777.63173570397	0.0534888264358287	0.726936500207331	353	modelBasic_total	0.0123	124
rs4970383	1	838555	A	C	-2.70012794265555	2.17867195354516	-1.23934580342023	0.217566025004361	2824.34196413237	0.0594708696112736	0.727699345499498	359	modelBasic_total	0.2339	124
rs4475691	1	846808	T	C	-1.47328548866513	2.33944711207393	-0.629757980448236	0.530014360388402	2825.47189275845	0.052632200446018	0.727888577432786	359	modelBasic_total	0.1694	124
rs142336952	1	853394	A	G	6.60417605349683	7.71465092921372	0.856056367824529	0.393608058617525	2777.63173570397	0.0534888264358287	0.726936500207331	353	modelBasic_total	0.0123	124
rs2341354	1	918573	A	G	-0.72996695315949	1.83703377666599	-0.397361748287664	0.691786177551442	2825.71004960227	0.0510635406241033	0.727883044919168	359	modelBasic_total	0.3911	124
rs1891910	1	932457	A	G	-2.10424347088426	2.03991795500077	-1.03153338384311	0.304336295809023	2802.41346678747	0.0566960400606542	0.729877648923114	356	modelBasic_total	0.2439	124
rs3128117	1	944564	C	T	-1.76744223187919	1.79856880696992	-0.98269369791686	0.327687448531142	2824.90585265697	0.056144250493417	0.727907813743213	359	modelBasic_total	0.4113	124
</pre>

Best,
Alejandro.

**Comment by welchr** [comment]
Can you attach your full metal script and error log here?

**Comment by AMCalejandro** [comment]
Sorry,

Apparently my meta file had a bug. I wrote it and ran it again. It seems that everything went fine. Apologies.

**Comment by nvice111** [comment]
it should not be 
OUTFILE metal_pdstat.ppmi.proband.opdc_totalOutcome.tbl
it should be 
OUTFILE metal_pdstat.ppmi.proband.opdc_totalOutcome .tbl

one more blank before .tbl
