### ISSUE TITLE
Effect column in output 

### ISSUE THREAD

**Issue by LindsayMMB** [statgen/METAL#18]
Hi,

I just wanted to clarify that the effect column in the meta-analysis output corresponds to "Beta" if the effect column in the input files was beta and one ran a meta-analysis using standard errors as the scheme. I can't find it written anywhere on METAL's wiki page.

Thank you in advance.

**Comment by welchr** [comment]
That should be the case as long as you used `EFFECTLABEL Beta` or `EFFECT Beta` in your METAL script for each input study.
