### ISSUE TITLE
Unexpected effective sample size when using sample overlap option

### ISSUE THREAD

**Issue by jean997** [statgen/METAL#26]
Hello,
I am meta-analyzing results from two GWAS. I know the sample overlap between the studies, which is about 80%. When I use the OVERLAP ON option, I find that the N column is never larger than the smaller of the two GWAS sample sizes. I would expect the larger of the two sample sizes to be the floor for N. Am I misinterpreting this column?
Thanks,
Jean

**Comment by jean997** [comment]
Marking resolved -- the issue was in file specification

**Comment by welchr** [comment]
Hi Jean - there are also some known bugs in the overlap method, one of which could cause the N value to be reported incorrectly. Try checking out https://github.com/welchr/METAL/tree/fix/sample-overlap if you run into issues. This should hopefully be merged into the main branch soon.
