### ISSUE TITLE
allele 1 vs. Effect allele in output file

### ISSUE THREAD

**Issue by PyunJung-Min** [statgen/METAL#35]
Hi, thanks for the wonderful tool.

I have a question about "allele 1" in the output file.

If I understood correctly, "allele 1 in the output file" is not always  effect allele, but could be effect allele or non-effect allele.
Is this right? 

If I like to know only effect alleles and their frequency/se/p-value of the meta-analysis output file, how can I  get it? 

I would appreciate for any help! 

Many thanks in advance.

Jung-Min Pyun

**Comment by welchr** [comment]
Allele frequencies and effect sizes are all oriented towards allele 1. This should be printed in the `.info` file that METAL produces. 

https://github.com/statgen/METAL/blob/ab5d19155aa72cef5ca5d2876aea0dd6b9fcba0d/metal/Main.cpp#L729-L735
