### ISSUE TITLE
How to calculate Cochran Q value in sample size model?

### ISSUE THREAD

**Issue by Y-Isaac** [statgen/METAL#44]
Hi, thanks for this useful tool.

I want to consult you that the process of calculation of Cochran Q value (also named HetChiSq in software). I have understood the heterogeneity calculation process in inverse variance weighting, but I am not quite sure how this process is implemented in sample size weighting. Is there a specific calculation formula for me to learn? I don't seem to be able to find the answer in the manuscript related to metal.

Best regard

**Comment by aoxiang88** [comment]
> Hi, thanks for this useful tool.
> 
> I want to consult you that the process of calculation of Cochran Q value (also named HetChiSq in software). I have understood the heterogeneity calculation process in inverse variance weighting, but I am not quite sure how this process is implemented in sample size weighting. Is there a specific calculation formula for me to learn? I don't seem to be able to find the answer in the manuscript related to metal.
> 
> Best regard

Hi Isaac,
I came across here with the same question. I didn't find any answer online and finally, I read the METAL codes. Here is the formula I learned:

Q = sum(square(Z_i - Z)), i for the i-th study
I2 = max{0, 100 * (Q - degree of freedom + 1)/Q}

Best,
Xiang

**Comment by Y-Isaac** [comment]
> > Hi, thanks for this useful tool.
> > I want to consult you that the process of calculation of Cochran Q value (also named HetChiSq in software). I have understood the heterogeneity calculation process in inverse variance weighting, but I am not quite sure how this process is implemented in sample size weighting. Is there a specific calculation formula for me to learn? I don't seem to be able to find the answer in the manuscript related to metal.
> > Best regard
> 
> Hi Isaac, I came across here with the same question. I didn't find any answer online and finally, I read the METAL codes. Here is the formula I learned:
> 
> Q = sum(square(Z_i - Z)), i for the i-th study I2 = max{0, 100 * (Q - degree of freedom + 1)/Q}
> 
> Best, Xiang

Thannnnnnnnnnnks!
