### ISSUE TITLE
Possible new feature? Keep genomic position in METAL output

### ISSUE THREAD

**Issue by Joannavonberg** [statgen/METAL#5]
Dear developers,

I've been using METAL with pleasure, it's understandable and user-friendly. However, I'm missing a feature (or am not aware of this feature) that would make it much easier to make Manhattan plots from the METAL output. Is it possible, or would it be possible, to tell METAL which column contains the genomic basepair position of the SNP and copy that column to the result file?

Best regards,
Joanna

**Comment by dtaliun** [comment]
Hi Joanna,

Please try the new version 2018-08-28.
First, in the beginning of your script you need to enable TRACKPOSITIONS ON.
Then, for each input file  you need to specify CHROMOSOME and POSITION labels e.g.:
CHROMOSOME chrom
POSITION pos

**Comment by Joannavonberg** [comment]
Great, thank you! I'm now running the new version.
