### ISSUE TITLE
how can I work out the allele frequency from the meta-analysis output?

### ISSUE THREAD

**Issue by summike** [statgen/METAL#6]
Hi, 
Thank you for sharing such a powerful tool for meta-analysis on GWAS!

For each SNP, the meta-analysed result contains information as SNP ID, Allele1, Allele2, Weight(N), Z score, P-value and Direction.

May I know how I can obtain the allele frequency from the output?

Thank you very much!
Best wishes,
Xiao

**Comment by welchr** [comment]
This should help: https://genome.sph.umich.edu/wiki/METAL_Documentation#Tracking_Allele_Frequencies
