### ISSUE TITLE
"OVERLAP ON" not processed

### ISSUE THREAD

**Issue by polpett** [statgen/METAL#7]
Hi everybody
I'm using METAL (version released on 2011-03-25) to perform a meta-analysis between several GWASs (genome-wide association studies). The included GWASs contain partly overlapping samples. I'm trying to correct for this source of bias by utilising the code "OVERLAP ON" suggested on the user guide (https://genome.sph.umich.edu/wiki/METAL_Documentation#Sample_Overlap_Correction).
But, in the log file, I realized that the code OVERLAP ON is not recognized by the software.

"## ERROR: The command you issued could not be processed ..."

How could I deal with this issue?

Many thanks in advance!!
Best wishes

**Comment by welchr** [comment]
Try grabbing the latest release from https://github.com/statgen/METAL/releases and [compiling it](https://github.com/statgen/METAL/releases). That should do the trick.
